# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
    - name: Publish Parent Pom
      run: mvn --batch-mode deploy -U -N
      env:
        GITHUB_TOKEN: ${{ secrets.FOR_PACKAGE_TOKEN }}
    - name: Publish kajundrama-spring-boot-lastest-parent
        run: |
          cd kajundrama-spring-boot-lastest-parent
          mvn --batch-mode deploy -U -N
      env:
        GITHUB_TOKEN: ${{ secrets.FOR_PACKAGE_TOKEN }}
    - name: Publish kajundrama-spring-boot-1.5.22-parent
        run: |
          cd kajundrama-spring-boot-1.5.22-parent
          mvn --batch-mode deploy -U -N
      env:
        GITHUB_TOKEN: ${{ secrets.FOR_PACKAGE_TOKEN }}
    - name: Publish kajundrama-min-dependency-parent
        run: |
          cd kajundrama-min-dependency-parent
          mvn --batch-mode deploy -U -N
      env:
        GITHUB_TOKEN: ${{ secrets.FOR_PACKAGE_TOKEN }}
    - name: Publish to GitHub Packages All Components
      run: mvn --batch-mode deploy -U
      env:
        GITHUB_TOKEN: ${{ secrets.FOR_PACKAGE_TOKEN }}
